//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift open source project
//
// Copyright (c) 2023 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://swift.org/LICENSE.txt for license information
// See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
//
//===----------------------------------------------------------------------===//

import Foundation
import Logging
import SystemPackage
import XCTest

@testable import SwiftSDKGenerator

final class EndToEndTests: XCTestCase {
  private let testcases = [
    #"""
      // Default program generated by swift package init
      print("Hello, world!")
    """#,
    #"""
      // Check that libc_nonshared.a is linked properly
      import Foundation

      func fin() -> Void {
        print("exiting")
      }

      atexit(fin)
    """#,
  ]

  private let logger = Logger(label: "swift-sdk-generator")

  #if !os(macOS)
  func testPackageInitExecutable() async throws {
    throw XCTSkip("EndToEnd tests currently deadlock under `swift test`: https://github.com/swiftlang/swift-sdk-generator/issues/143")

    let fm = FileManager.default

    var packageDirectory = FilePath(#filePath)
    packageDirectory.removeLastComponent()
    packageDirectory.removeLastComponent()

    // Do multiple runs with different sets of arguments.
    // Test with no arguments by default:
    var possibleArguments = [""]
    do {
      try await Shell.run("docker ps")
      possibleArguments.append("--with-docker --linux-distribution-name rhel --linux-distribution-version ubi9")
    } catch {
      self.logger.warning("Docker CLI does not seem to be working, skipping tests that involve Docker.")
    }

    for runArguments in possibleArguments {
      let generatorOutput = try await Shell.readStdout(
        "cd \(packageDirectory) && swift run swift-sdk-generator \(runArguments)"
      )

      let installCommand = try XCTUnwrap(generatorOutput.split(separator: "\n").first {
        $0.contains("swift experimental-sdk install")
      })

      let bundleName = try XCTUnwrap(
        FilePath(String(XCTUnwrap(installCommand.split(separator: " ").last))).components.last
      ).stem

      let installedSDKs = try await Shell.readStdout("swift experimental-sdk list").components(separatedBy: "\n")

      // Make sure this bundle hasn't been installed already.
      if installedSDKs.contains(bundleName) {
        try await Shell.run("swift experimental-sdk remove \(bundleName)")
      }

      let installOutput = try await Shell.readStdout(String(installCommand))
      XCTAssertTrue(installOutput.contains("successfully installed"))

      for testcase in self.testcases {
        let testPackageURL = FileManager.default.temporaryDirectory.appendingPathComponent("swift-sdk-generator-test")
        let testPackageDir = FilePath(testPackageURL.path)
        try? fm.removeItem(atPath: testPackageDir.string)
        try fm.createDirectory(atPath: testPackageDir.string, withIntermediateDirectories: true)

        try await Shell.run("swift package --package-path \(testPackageDir) init --type executable")
        let main_swift = testPackageURL.appendingPathComponent("Sources/main.swift")
        try testcase.write(to: main_swift, atomically: true, encoding: .utf8)

        var buildOutput = try await Shell.readStdout(
          "swift build --package-path \(testPackageDir) --experimental-swift-sdk \(bundleName)"
        )
        XCTAssertTrue(buildOutput.contains("Build complete!"))
        try await Shell.run("rm -rf \(testPackageDir.appending(".build"))")
        buildOutput = try await Shell.readStdout(
          "swift build --package-path \(testPackageDir) --experimental-swift-sdk \(bundleName) --static-swift-stdlib"
        )
        XCTAssertTrue(buildOutput.contains("Build complete!"))
      }
    }
  }

  func testRepeatedSDKBuilds() async throws {
    throw XCTSkip("EndToEnd tests currently deadlock under `swift test`: https://github.com/swiftlang/swift-sdk-generator/issues/143")

    var packageDirectory = FilePath(#filePath)
    packageDirectory.removeLastComponent()
    packageDirectory.removeLastComponent()

    // Test that an existing SDK can be rebuilt without cleaning up.
    // Test with no arguments by default:
    var possibleArguments = [""]
    do {
      try await Shell.run("docker ps")
      possibleArguments.append("--with-docker --linux-distribution-name rhel --linux-distribution-version ubi9")
    } catch {
      self.logger.warning("Docker CLI does not seem to be working, skipping tests that involve Docker.")
    }

    for runArguments in possibleArguments {
      let firstGeneratorOutput = try await Shell.readStdout(
        "cd \(packageDirectory) && swift run swift-sdk-generator \(runArguments)"
      )
      XCTAssert(firstGeneratorOutput.contains("swift experimental-sdk install"))

      let repeatGeneratorOutput = try await Shell.readStdout(
        "cd \(packageDirectory) && swift run swift-sdk-generator \(runArguments)"
      )
      XCTAssert(repeatGeneratorOutput.contains("swift experimental-sdk install"))
    }
  }
  #endif
}
